# Generated by Django 4.2.2 on 2023-08-11 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_discount_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name_plural': 'Bateries'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='graphics',
            options={'verbose_name_plural': 'Graphics'},
        ),
        migrations.AlterModelOptions(
            name='powersupply',
            options={'verbose_name_plural': 'Power supplies'},
        ),
        migrations.RenameField(
            model_name='productversion',
            old_name='processore',
            new_name='processor',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='processor_technology',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.productversion'),
        ),
        migrations.DeleteModel(
            name='ProcessorTechnology',
        ),
    ]
