# Generated by Django 4.2.2 on 2023-08-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_battery_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_version',
        ),
    ]
