# Generated by Django 4.2.2 on 2023-08-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_product_productimage_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.AddField(
            model_name='productreview',
            name='product_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='store.productversion'),
        ),
    ]
