# Generated by Django 4.2.2 on 2023-08-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productreview_slug_productversion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
