# Generated by Django 4.2.2 on 2023-08-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productreview_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='store.productversion'),
        ),
    ]
