# Generated by Django 4.2.2 on 2023-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productversion_options_alter_discount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.FloatField(verbose_name='Discount in %'),
        ),
    ]
