# Generated by Django 4.2.2 on 2023-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/profile_images/default.jpg', null=True, upload_to='profile_images/', verbose_name='image'),
        ),
    ]
