# Generated by Django 4.2.2 on 2023-08-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_description_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogreview',
            options={'ordering': ['-created_at']},
        ),
    ]
