# Generated by Django 4.2.2 on 2023-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogreview_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreview',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
