# Generated by Django 4.2.2 on 2023-09-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogreview_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
    ]
