# Generated by Django 4.2.2 on 2023-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='blogreview',
            name='slug',
            field=models.SlugField(blank=True, max_length=10000, null=True),
        ),
    ]
